### ISSUE TITLE
Can't find the blueprint in tech tree

### ISSUE THREAD

**Issue by leeyachan** [HappyGingerWolf/Elementary#3]
Hey dude, I really like your mod but I think you forgot to add the machines into the tech tree cuz I can't really find them. If you have updated the mod or find there is no problem, please let me know, thanks.

**Comment by HappyGingerWolf** [comment]
I didn't forget, it's just that the mod is partially finished and I had to stop working on it to do other things. Hopefully I can come back to it and finish it all.

**Comment by leeyachan** [comment]
I hope that you can put what's already done in it because the fact that laser drills take steels to built but I can't make steel without those machines. Also the lithium is required for making cryofluid. I really like the style of this mod and I want to play it even if it is unfinished. Hope you will upload the tech tree. Thanks.

**Comment by HappyGingerWolf** [comment]
Yeah, I know it breaks campaign rn, I'll sort it as soon as I'm able to

**Comment by HappyGingerWolf** [comment]
Yeah, I know it breaks campaign rn, I'll sort it as soon as I'm able to

**Comment by leeyachan** [comment]
Thanks a lot, love you and your mod.<3
